import React,{useReducer,useState,useEffect,useRef} from 'react';
import {Building2,BookOpen,PlusCircle,RotateCcw,Rotate3D,ZoomIn,ZoomOut,Scan,Volume2,VolumeX,ArrowUpRight,ArrowRight,ChevronRight,X,Flag,Home,Wallet,MapPin,Trophy,Dices,Check,Landmark,TreePine} from 'lucide-react';
import Board from './Board.jsx';
import SaveManager from './SaveManager.jsx';
import {saveAuto,listSaves} from './storage.js';
import {reducer,loadGame,TILES,COLORS,money,ownLots,worth,rent,canBuild,buildCost,availableBuildings} from './game.js';

function Dice({value,rolling}){const dots={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};return <div className={'die '+(rolling?'rolling':'')} aria-label={`${value} 點`}>{Array.from({length:9},(_,i)=><i key={i} className={dots[value].includes(i+1)?'pip':''}/>)}</div>;}
function playerColor(p){return p?.color||COLORS[p?.id||0];}
function Avatar({id,small=false,player}){return <span className={'avatar '+(small?'small':'')} style={{'--player':playerColor(player||{id})}}><span className="avatar-head"/><span className="avatar-body"/><span className="avatar-cap"/><span className="owner-number">{id+1}</span></span>;}
function buildingLabel(level){return level===5?'旅館':level?`${level} 間房屋`:'未開發地產';}
function buildingLevelText(level){return level===5?'旅館':'房屋 '+(level||0)+' / 4';}
function buildHelp(game,t,l){
 if(game.selected!==t.id||game.stage!=='end')return '走到自己的土地時，才能在當下建造。';
 if(game.buildUsed)return '本次落地已完成建造。';
 if(l.level===5)return '這塊土地已有旅館。';
 const bank=availableBuildings(game);
 if(l.level===4)return bank.hotels?'你剛走到這塊土地，可以升級為旅館。':'銀行旅館已用完。';
 return bank.houses?'你剛走到自己的土地，可以加蓋一間房屋。':'銀行房屋已用完。';
}
function buildButtonLabel(game,t,l){
 if(l.level===5)return '已達最高等級';
 if(game.buildUsed&&game.selected===t.id)return '本次落地已建造';
 return l.level===4?`升級旅館 · ${money(buildCost(t))}`:`建造房屋 · ${money(buildCost(t))}`;
}
function Modal({title,onClose,children,wide=false}){const dialog=useRef();useEffect(()=>{const old=document.activeElement;dialog.current?.focus();function keys(e){if(e.key==='Escape')onClose?.();if(e.key==='Tab'){const els=[...dialog.current.querySelectorAll('button:not(:disabled),a,input,[tabindex="0"]')];if(!els.length){e.preventDefault();return;}if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);old?.focus();};},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><section ref={dialog} tabIndex={-1} className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title}><div className="modal-heading"><h2>{title}</h2>{onClose&&<button className="icon-button" aria-label="關閉" onClick={onClose}><X size={20}/></button>}</div>{children}</section></div>;}
const rules=[['擲骰與移動','你與 3 位電腦輪流擲兩顆骰子，3D 棋子按點數前進。通過起點領取 $2,000；雙骰相同不追加回合。'],['購地與租金','停在無主地產可按標價購買，也可跳過。停在對手地產即支付租金；同色地產收齊後，空地租金加倍。'],['房屋與旅館','只要走到自己的土地，就能在該次落地決定是否建造；不需要集齊同色地產，每次落地最多建造 1 次。每次建造費為地價的 60%；最多 4 間房屋，已有 4 間房屋時再次走到該地可升級為旅館。租金倍率依序為 3、6、10、15，旅館為 22。'],['城市中的驚喜','機會與城市基金帶來獎勵或支出。所得稅 $1,200，奢侈稅 $1,800。前往監獄會移到探訪監獄格並暫停下一回合；免費停車不收費。'],['資金與勝利','現金不足付款時，系統由低價地產開始，以地價和升級成本合計的 50% 自動變賣；仍不足就破產。最後存活者獲勝；若設定回合上限，達到上限後以現金＋地產原價＋升級成本最高者獲勝。'],['你的遊戲，自動保留','每個穩定回合自動儲存在這個瀏覽器。重新整理可繼續；新遊戲會清除原進度。本作採自訂快速規則，未加入拍賣、抵押或玩家間交易。']];
function parseRoundLimit(setup){if(setup.roundOption==='unlimited')return null;if(setup.roundOption==='custom'){const value=Number(setup.customRounds);return Number.isInteger(value)&&value>=1?value:null;}return Number(setup.roundOption);}
export default function App(){
 const [game,dispatch]=useReducer(reducer,undefined,loadGame),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[tab,setTab]=useState('players'),[sound,setSound]=useState(false),[rotating,setRotating]=useState(false),[error,setError]=useState(''),[saveError,setSaveError]=useState(false),[setup,setSetup]=useState({count:4,roundOption:'40',customRounds:'100',players:[{name:'你',color:COLORS[0],human:true},{name:'艾米',color:COLORS[1],human:false},{name:'小傑',color:COLORS[2],human:false},{name:'喵喵',color:COLORS[3],human:false}]});
 const board=useRef(),audio=useRef();const player=game.players[game.turn],human=!!player?.human&&!player?.bankrupt;const active=human&&['ready','end'].includes(game.stage);
 const roll=()=>{dispatch({type:'ROLL',dice:[1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)],eventIndex:Math.floor(Math.random()*6)});};
 useEffect(()=>{try{listSaves();}catch{setSaveError(true);}},[]);
 useEffect(()=>{if(game.stage!=='moving')try{saveAuto(game);setSaveError(false);}catch{setSaveError(true);}},[game]);
 useEffect(()=>{if(game.stage==='moving'&&modal!=='saves'){const timer=setTimeout(()=>dispatch({type:'STEP'}),330);return()=>clearTimeout(timer);}},[game,modal]);
 useEffect(()=>{
  const landedId=game.selected;
  const landedTile=landedId===null?null:TILES[landedId];
  const landedLot=landedId===null?null:game.lots[landedId];
  const shouldOpenPurchase=human&&game.stage==='decision'&&landedTile?.type==='property'&&!landedLot;
  const shouldOpenBuild=human&&game.stage==='end'&&game.buildAvailable&&landedLot?.owner===game.turn;
  if(shouldOpenPurchase||shouldOpenBuild){
   setSelected(landedId);
   setModal('property');
  }
 },[game,human]);
 useEffect(()=>{if(human||game.stage==='finished'||modal==='new'||modal==='rules'||modal==='saves')return;const timer=setTimeout(()=>{if(game.stage==='ready')roll();else if(game.stage==='decision')dispatch({type:player.cash>TILES[player.pos].price+1800?'BUY':'SKIP'});else if(game.stage==='end'){const t=ownLots(game,game.turn).find(t=>canBuild(game,t.id)&&player.cash>Math.round(t.price*.6)+2500);if(t)dispatch({type:'BUILD',id:t.id});else dispatch({type:'NEXT'});}},game.stage==='decision'?1300:1100);return()=>clearTimeout(timer);},[game,human,modal]);
 useEffect(()=>{if(!sound||!audio.current)return;try{const ctx=audio.current,o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.type='sine';o.frequency.setValueAtTime(game.stage==='moving'?380:620,ctx.currentTime);g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);o.start();o.stop(ctx.currentTime+.15);}catch{}},[game.remaining,game.stage,sound]);
 const toggleSound=()=>{if(!sound){const A=window.AudioContext||window.webkitAudioContext;if(A){audio.current ||= new A();audio.current.resume();}}setSound(!sound);};
 const inspect=id=>{setSelected(id);setModal('property');};
 const newGameMaxRounds=parseRoundLimit(setup);
 const startNew=()=>{if(setup.roundOption==='custom'&&!newGameMaxRounds)return;dispatch({type:'NEW',config:{...setup,maxRounds:newGameMaxRounds}});setModal(null);setTab('players');board.current?.reset();setRotating(false);};
 const t=selected!==null?TILES[selected]:null,l=t?game.lots[t.id]:null;const landed=TILES[player.pos];
 const purchaseAvailable=!!t&&t.type==='property'&&!l&&game.stage==='decision'&&human&&landed.id===t.id;
 return <div className="app-shell">
  <header className="header"><a className="brand" href="./" aria-label="城市大亨首頁"><span className="brand-icon"><Building2 size={33} strokeWidth={1.8}/></span><span><strong>城市大亨</strong><small>CITY TYCOON</small></span></a><p className="tagline">玩一場，擁有一座城。</p><nav><button className="text-button" aria-label="遊戲規則" onClick={()=>setModal('rules')}><BookOpen size={18}/><span>遊戲規則</span></button><span className="nav-divider"/><button className="outline-button" onClick={()=>setModal('new')}><PlusCircle size={18}/><span>新遊戲</span></button></nav></header>
  <button className="save-launch secondary" onClick={()=>setModal('saves')}>儲存／讀取</button>
  {modal==='saves'&&<Modal title="存檔管理" wide onClose={()=>setModal(null)}><SaveManager game={game} onLoad={saved=>{dispatch({type:'LOAD',game:saved});try{saveAuto(saved);setSaveError(false);}catch{setSaveError(true);}setSelected(null);setTab('players');setModal(null);}}/></Modal>}
  <main className="game-layout"><section className="world" aria-label="遊戲棋盤">
   <Board game={game} onSelect={inspect} onError={setError} ref={board}/>
   <div className="world-heading"><span className="live-dot"/>經典城市 <span className="world-heading-divider">/</span><span>4 人對局</span></div>
   <div className="world-top-right"><span className="saved"><Check size={13}/>{saveError?'此瀏覽器無法存檔':'自動儲存'}</span><button className="icon-button sound" aria-label={sound?'關閉音效':'開啟音效'} onClick={toggleSound}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div>
   {error&&<div className="webgl-error">{error}</div>}
   <div className="board-foot"><div className="camera-toolbar"><button title="自動旋轉視角" aria-label="自動旋轉視角" className={rotating?'selected':''} onClick={()=>{board.current?.rotate();setRotating(!rotating);}}><Rotate3D size={20}/><span>旋轉視角</span></button><button title="重置視角" aria-label="重置視角" onClick={()=>{board.current?.reset();setRotating(false);}}><RotateCcw size={18}/></button><button title="俯視棋盤" aria-label="俯視棋盤" onClick={()=>board.current?.top()}><Scan size={18}/></button><i/><button title="縮小" aria-label="縮小" onClick={()=>board.current?.zoom(1.15)}><ZoomOut size={20}/></button><button title="放大" aria-label="放大" onClick={()=>board.current?.zoom(.87)}><ZoomIn size={20}/></button></div><span className="gesture-hint">拖曳旋轉 · 滾輪縮放 · 點選地產</span></div>
  </section>
   <aside className="sidebar"><div className="round-heading"><div><span className="round-caption">城市的每一步，由你決定</span><h1>回合 <b>{String(game.round).padStart(2,'0')}</b><span>/ {game.maxRounds===null?'∞':game.maxRounds}</span></h1></div><span className="round-icon"><Flag size={21}/></span></div>
   <div className="tabs"><button className={tab==='players'?'active':''} onClick={()=>setTab('players')}>玩家概況</button><button className={tab==='properties'?'active':''} onClick={()=>setTab('properties')}>我的地產 <span>{ownLots(game,0).length}</span></button></div>
   <div className="overview">{tab==='players'?game.players.map(p=><div key={p.id} className={'player-row '+(game.turn===p.id?'current ':'')+(p.bankrupt?'bankrupt':'')} style={{'--player':playerColor(p)}}><Avatar id={p.id} player={p}/><div className="player-info"><strong>{p.name}{p.id===0?<em>玩家</em>:<span className="ai">電腦</span>}</strong><small>{p.bankrupt?'已破產':`${ownLots(game,p.id).length} 塊地產${p.jail?' · 監獄中':''}`}</small></div><div className="player-cash"><b>{money(p.cash)}</b>{game.turn===p.id&&<small><span/> 目前回合</small>}</div></div>):<div className="property-list">{ownLots(game,0).length?ownLots(game,0).map(t=><button key={t.id} onClick={()=>inspect(t.id)}><i style={{background:t.color}}/><span><strong>{t.name}</strong><small>{buildingLabel(game.lots[t.id].level)} · 租金 {money(rent(game,t))}</small></span><ChevronRight size={16}/></button>):<div className="empty-properties"><Home size={28}/><strong>你的第一塊地產，正在等你</strong><p>擲骰探索城市，停在無主街區即可購買。</p></div>}</div>}</div>
   <section className="turn-panel" aria-live="polite"><div className="turn-title"><span className="live-dot" style={{background:playerColor(player)}}/><h2>{game.stage==='finished'?'本局已結束':human?'你的回合':`${player.name}的回合`}</h2><span>{game.stage==='moving'?'移動中':game.stage==='decision'?'購地時刻':human?'準備出發':'電腦玩家'}</span></div>
    <div className="dice-row"><Dice value={game.dice[0]} rolling={game.stage==='moving'}/><Dice value={game.dice[1]} rolling={game.stage==='moving'}/></div>
    {game.stage==='finished'?<button className="primary" onClick={()=>setModal('result')}><Trophy size={19}/>查看結算</button>:human&&game.stage==='decision'?<div className="buy-actions"><div className="buy-summary"><strong>{landed.name}</strong><b>{money(landed.price)}</b></div><button className="primary" onClick={()=>dispatch({type:'BUY'})}><Home size={18}/>購買地產</button><button className="skip-button" onClick={()=>dispatch({type:'SKIP'})}>暫不購買，保留現金 <ArrowRight size={14}/></button></div>:<button className="primary" disabled={!human||game.stage==='moving'} onClick={()=>game.stage==='end'?dispatch({type:'NEXT'}):roll()}>{game.stage==='moving'?<>前進中 · 還有 {game.remaining} 格</>:!human?<>電腦思考中<span className="thinking">…</span></>:game.stage==='end'?<>結束回合 <ArrowRight size={19}/></>:<><Dices size={21}/>擲骰子</>}</button>}
    <p className="turn-hint">{game.stage==='ready'?(human?'好運從這一步開始。':'下一段城市冒險，即將展開。'):game.notice}</p>
    {game.event&&<div className="event-note"><img src="./chance.png" alt="城市機會卡"/><div><strong>{game.event.title}</strong><span>{game.event.amount>0?'+':'−'} {money(Math.abs(game.event.amount))}</span></div></div>}
   </section>
   <section className="activity"><div className="activity-heading"><h2>城市動態</h2><button onClick={()=>setModal('log')}>全部紀錄 <ArrowUpRight size={14}/></button></div><div className="activity-list">{game.log.slice(0,3).map((e,i)=><div className="activity-item" key={i}><span className={'event-icon '+e.kind}>{e.kind==='buy'?<Home size={16}/>:e.kind==='dice'?<Dices size={16}/>:e.kind==='tax'?<Landmark size={16}/>:<ArrowUpRight size={16}/>}</span><p>{e.text}<small>{i===0?'剛剛':'本局紀錄'}</small></p></div>)}</div></section>
   <footer className="sidebar-footer"><span className="mini-dot"/>一起，把城市變成你的故事。</footer>
  </aside></main>
  {modal==='rules'&&<Modal title="城市大亨 · 遊戲規則" wide onClose={()=>setModal(null)}><p className="modal-lead">買下喜歡的街區，把小小投資變成一座城市。</p><div className="rules-list">{rules.map(([title,body],i)=><div key={title}><span>{String(i+1).padStart(2,'0')}</span><section><h3>{title}</h3><p>{body}</p></section></div>)}</div><button className="primary" onClick={()=>setModal(null)}>知道了，回到城市 <ArrowRight size={18}/></button></Modal>}
  {modal==='new'&&<Modal title="開啟一段全新的城市故事" onClose={()=>setModal(null)}><img className="modal-art" src="./chance.png" alt="微縮城市與機會信封"/><p className="modal-lead">設定參與玩家與遊戲長度後開始新遊戲。每位玩家各帶著 $15,000 出發。</p><label className="setup-count">玩家人數 <select value={setup.count} onChange={e=>setSetup(s=>({...s,count:Number(e.target.value)}))}>{[2,3,4].map(n=><option key={n} value={n}>{n} 人</option>)}</select></label><label className="setup-count">最多回合 <select aria-label="最多回合" value={setup.roundOption} onChange={e=>setSetup(s=>({...s,roundOption:e.target.value}))}><option value="40">40 回合</option><option value="80">80 回合</option><option value="custom">自訂</option><option value="unlimited">無限制</option></select></label>{setup.roundOption==='custom'&&<label className="round-limit-custom">自訂回合數<input aria-label="自訂回合數" type="number" min="1" step="1" value={setup.customRounds} onChange={e=>setSetup(s=>({...s,customRounds:e.target.value}))}/></label>}<div className="player-setup">{setup.players.slice(0,setup.count).map((p,i)=><div className="player-setup-row" key={i}><input aria-label={`玩家 ${i+1} 名稱`} value={p.name} onChange={e=>setSetup(s=>({...s,players:s.players.map((x,j)=>j===i?{...x,name:e.target.value}:x)}))}/><input aria-label={`玩家 ${i+1} 顏色`} type="color" value={p.color} onChange={e=>setSetup(s=>({...s,players:s.players.map((x,j)=>j===i?{...x,color:e.target.value}:x)}))}/><select value={p.human?'human':'ai'} onChange={e=>setSetup(s=>({...s,players:s.players.map((x,j)=>j===i?{...x,human:e.target.value==='human'}:x)}))}><option value="human">真人</option><option value="ai">電腦</option></select></div>)}</div><button className="primary" disabled={setup.roundOption==='custom'&&!newGameMaxRounds} onClick={startNew}><PlusCircle size={18}/>開始新遊戲</button><button className="secondary full" onClick={()=>setModal(null)}>繼續目前遊戲</button></Modal>}
   {modal==='property'&&t&&<Modal title="地產手冊" onClose={()=>setModal(null)}><div className="property-card" style={{'--lot':t.color}}><div className="property-banner">{t.type==='property'?'CITY PROPERTY':'CITY DESTINATION'}</div><MapPin size={24}/><h3>{t.name}</h3><p>{t.type==='property'?`街區 ${t.group+1} · ${l?`${game.players[l.owner].name}的地產`:'尚未出售'}`:'城市公共空間'}</p></div>{t.type==='property'?<><div className="property-stats"><div><span>地產價格</span><b>{money(t.price)}</b></div><div><span>目前租金</span><b>{money(l?rent(game,t):Math.round(t.price*.18))}</b></div><div><span>建築等級</span><b>{buildingLevelText(l?.level)}</b></div><div><span>建造費</span><b>{money(buildCost(t))}</b></div></div>{l?.owner===player.id?<><p className="property-help">{buildHelp(game,t,l)}</p><button className="primary" disabled={!active||!canBuild(game,t.id,player.id)} onClick={()=>dispatch({type:'BUILD',id:t.id})}><Building2 size={18}/>{buildButtonLabel(game,t,l)}</button><button className="secondary full" disabled={!active} onClick={()=>{dispatch({type:'SELL',id:t.id});setModal(null);}}>變賣地產 · {money(Math.floor((t.price+l.level*buildCost(t))*.5))}</button></>:purchaseAvailable?<><p className="property-help">本次落地可以購買這塊地產。</p><button className="primary" onClick={()=>dispatch({type:'BUY'})}><Home size={18}/>購買地產 · {money(t.price)}</button><button className="secondary full" onClick={()=>{dispatch({type:'SKIP'});setModal(null);}}>暫不購買，保留現金</button></>:<p className="property-help">{l?'停留在此需向擁有者支付租金。':'擲骰移動到此，即可購買這塊地產。'}</p>}</>:<p className="property-help">{t.type==='start'?'每次經過起點，領取 $2,000。':t.type==='chance'||t.type==='fund'?'抽一張城市事件卡，看看今天有什麼驚喜。':t.type==='gojail'?'前往監獄並暫停下一回合。':t.type==='tax'?`停在這裡支付 ${t.id===6?'$1,200':'$1,800'} 稅金。`:t.type==='jail'?'路過僅探訪；由前往監獄格送入才需暫停。':'免費休息，不支付任何費用。'}</p>}</Modal>}
  {modal==='log'&&<Modal title="本局城市紀錄" onClose={()=>setModal(null)}><div className="full-log">{game.log.map((e,i)=><p key={i}><span>{String(game.log.length-i).padStart(2,'0')}</span>{e.text}</p>)}</div></Modal>}
  {(modal==='result'||game.stage==='finished'&&modal===null)&&<Modal title="這座城市，有了新的大亨" onClose={()=>setModal('closedResult')}><div className="winner"><Trophy size={42}/><h3>{game.players[game.winner]?.name}獲勝！</h3><p>城市的每一步，成就你的不凡眼光。</p></div><div className="rankings">{[...game.players].sort((a,b)=>worth(game,b.id)-worth(game,a.id)).map((p,i)=><div key={p.id}><b>{i+1}</b><Avatar id={p.id} player={p} small/><strong>{p.name}</strong><span>{p.bankrupt?'已破產':money(worth(game,p.id))}</span></div>)}</div><p className="property-help">總資產＝現金＋地產原價＋房屋建造成本</p><button className="primary" onClick={startNew}>再玩一場 <ArrowRight size={18}/></button></Modal>}
 </div>;
}
