import test from 'node:test';
import assert from 'node:assert/strict';
import {freshGame,reducer,TILES,rent,canBuild,worth} from './game.js';
function travel(s,dice=[1,1],eventIndex=0){s=reducer(s,{type:'ROLL',dice,eventIndex});while(s.stage==='moving')s=reducer(s,{type:'STEP'});return s;}
test('buy once, preserve input, and transfer rent to owner',()=>{let initial=freshGame();let s=travel(initial);assert.equal(s.players[0].pos,2);assert.equal(s.stage,'decision');s=reducer(s,{type:'BUY'});assert.equal(s.players[0].cash,13800);assert.equal(initial.players[0].cash,15000);assert.equal(s.lots[2].owner,0);assert.strictEqual(reducer(s,{type:'BUY'}),s);s=reducer(s,{type:'NEXT'});s=travel(s);assert.equal(s.players[1].cash,15000-216);assert.equal(s.players[0].cash,13800+216);});
test('pass GO exactly once, even when landing after it',()=>{let s=freshGame();s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(s.players[0].cash,17000);assert.equal(s.players[0].pos,1);});
test('any owned property can build one house when landed, without a color group',()=>{let s=freshGame();s.lots[1]={owner:0,level:0};assert.equal(canBuild(s,1),false);s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(s.players[0].pos,1);assert.equal(s.stage,'end');assert.equal(canBuild(s,1),true);s=reducer(s,{type:'BUILD',id:1});assert.equal(s.lots[1].level,1);assert.equal(s.buildUsed,true);assert.equal(canBuild(s,1),false);assert.equal(rent(s,TILES[1]),594);});
test('four houses upgrade to a hotel on a later landing',()=>{let s=freshGame();s.lots[1]={owner:0,level:4};s.bank={houses:28,hotels:12};s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(canBuild(s,1),true);s=reducer(s,{type:'BUILD',id:1});assert.equal(s.lots[1].level,5);assert.deepEqual(s.bank,{houses:32,hotels:11});assert.equal(rent(s,TILES[1]),4356);assert.equal(canBuild(s,1),false);});
test('complete color group doubles only unimproved rent',()=>{let s=freshGame();s.lots[1]={owner:0,level:0};s.lots[2]={owner:0,level:0};assert.equal(rent(s,TILES[1]),396);s.lots[1].level=1;assert.equal(rent(s,TILES[1]),594);assert.equal(worth(s,0),17960);});
test('tax liquidates property before declaring insolvency',()=>{let s=freshGame();s.players[0].cash=100;s.lots[2]={owner:0,level:0};s.players[0].pos=4;s=travel(s);assert.equal(s.players[0].bankrupt,true);assert.equal(s.players[0].cash,0);assert.equal(s.lots[2],undefined);});
test('liquidation rescues a player when proceeds cover payment',()=>{let s=freshGame();s.players[0].cash=1100;s.lots[2]={owner:0,level:0};s.players[0].pos=4;s=travel(s);assert.equal(s.players[0].bankrupt,false);assert.equal(s.players[0].cash,500);});
test('go to jail skips one turn and resumes normally',()=>{let s=freshGame();s.players[0].pos=22;s=travel(s);assert.equal(s.players[0].pos,8);assert.equal(s.players[0].jail,1);s.stage='ready';s=travel(s);assert.equal(s.players[0].pos,8);assert.equal(s.players[0].jail,0);assert.equal(s.stage,'end');s.stage='ready';s=travel(s);assert.equal(s.players[0].pos,10);});
test('chance award and expense correctly resolve without extra action',()=>{let s=freshGame();s.players[0].pos=1;s=travel(s,[1,1],0);assert.equal(s.players[0].cash,16500);assert.equal(s.event.title,'城市更新獎勵');s=freshGame();s.players[0].pos=1;s=travel(s,[1,1],1);assert.equal(s.players[0].cash,14100);});
test('bankrupt turns are skipped and final survivor wins',()=>{let s=freshGame();s.players[1].bankrupt=true;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.turn,2);s=freshGame();s.players[1].bankrupt=s.players[2].bankrupt=true;s.turn=3;s.players[3].cash=0;s.players[3].pos=4;s=travel(s);assert.equal(s.stage,'finished');assert.equal(s.winner,0);});
test('40 round ending selects highest solvent net worth',()=>{let s=freshGame();s.round=40;s.turn=3;s.stage='end';s.players[2].cash=21000;s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'finished');assert.equal(s.winner,2);});
test('simulate 100 complete games: finite turns, no negative funds or invalid owners',()=>{let seed=17;const rnd=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n;};for(let g=0;g<100;g++){let s=freshGame(),actions=0;while(s.stage!=='finished'&&actions++<10000){if(s.stage==='ready')s=travel(s,[rnd(6)+1,rnd(6)+1],rnd(6));else if(s.stage==='decision')s=reducer(s,{type:rnd(4)?'BUY':'SKIP'});else if(s.stage==='end'){let t=TILES.find(t=>canBuild(s,t.id));if(t&&rnd(3)===0)s=reducer(s,{type:'BUILD',id:t.id});else s=reducer(s,{type:'NEXT'});}for(const p of s.players)assert.ok(p.cash>=0);for(const l of Object.values(s.lots))assert.equal(s.players[l.owner].bankrupt,false);}assert.equal(s.stage,'finished');assert.ok(actions<10000);}});
