import test from 'node:test';
import assert from 'node:assert/strict';
import {freshGame,reducer,TILES,rent,canBuild,worth,inflationAmount,propertyPrice,buildCost,MAX_PRICE_INDEX} from './game.js';
function travel(s,dice=[1,1],eventIndex=0){s=reducer(s,{type:'ROLL',dice,eventIndex});while(s.stage==='moving')s=reducer(s,{type:'STEP'});return s;}
test('buy once, preserve input, and transfer rent to owner',()=>{let initial=freshGame();let s=travel(initial);assert.equal(s.players[0].pos,2);assert.equal(s.stage,'decision');s=reducer(s,{type:'BUY'});assert.equal(s.players[0].cash,13800);assert.equal(initial.players[0].cash,15000);assert.equal(s.lots[2].owner,0);assert.strictEqual(reducer(s,{type:'BUY'}),s);s=reducer(s,{type:'NEXT'});s=travel(s);assert.equal(s.players[1].cash,15000-216);assert.equal(s.players[0].cash,13800+216);});
test('pass GO exactly once, even when landing after it',()=>{let s=freshGame();s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(s.players[0].cash,17000);assert.equal(s.players[0].pos,1);});
test('any owned property can build one house when landed, without a color group',()=>{let s=freshGame();s.lots[1]={owner:0,level:0};assert.equal(canBuild(s,1),false);s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(s.players[0].pos,1);assert.equal(s.stage,'end');assert.equal(canBuild(s,1),true);s=reducer(s,{type:'BUILD',id:1});assert.equal(s.lots[1].level,1);assert.equal(s.buildUsed,true);assert.equal(canBuild(s,1),false);assert.equal(rent(s,TILES[1]),594);});
test('four houses upgrade to a hotel on a later landing',()=>{let s=freshGame();s.lots[1]={owner:0,level:4};s.bank={houses:28,hotels:12};s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(canBuild(s,1),true);s=reducer(s,{type:'BUILD',id:1});assert.equal(s.lots[1].level,5);assert.deepEqual(s.bank,{houses:32,hotels:11});assert.equal(rent(s,TILES[1]),4356);assert.equal(canBuild(s,1),false);});
test('building inventory can be limited or unlimited',()=>{let limited=freshGame({limitBuildings:true});limited.lots[1]={owner:0,level:0};limited.players[0].pos=1;limited.stage='end';limited.selected=1;limited.buildAvailable=true;limited.bank.houses=0;assert.equal(canBuild(limited,1),false);let unlimited=freshGame({limitBuildings:false});unlimited.lots[1]={owner:0,level:0};unlimited.players[0].pos=1;unlimited.stage='end';unlimited.selected=1;unlimited.buildAvailable=true;unlimited.bank.houses=0;assert.equal(canBuild(unlimited,1),true);unlimited=reducer(unlimited,{type:'BUILD',id:1});assert.equal(unlimited.lots[1].level,1);assert.deepEqual(unlimited.bank,{houses:32,hotels:12});});
test('complete color group doubles only unimproved rent',()=>{let s=freshGame();s.lots[1]={owner:0,level:0};s.lots[2]={owner:0,level:0};assert.equal(rent(s,TILES[1]),396);s.lots[1].level=1;assert.equal(rent(s,TILES[1]),594);assert.equal(worth(s,0),17960);});
test('tax liquidates property before declaring insolvency',()=>{let s=freshGame();s.players[0].cash=100;s.lots[2]={owner:0,level:0};s.players[0].pos=4;s=travel(s);assert.equal(s.players[0].bankrupt,true);assert.equal(s.players[0].cash,0);assert.equal(s.lots[2],undefined);});
test('liquidation rescues a player when proceeds cover payment',()=>{let s=freshGame();s.players[0].cash=1100;s.lots[2]={owner:0,level:0};s.players[0].pos=4;s=travel(s);assert.equal(s.players[0].bankrupt,false);assert.equal(s.players[0].cash,500);});
test('go to jail skips one turn and resumes normally',()=>{let s=freshGame();s.players[0].pos=22;s=travel(s);assert.equal(s.players[0].pos,8);assert.equal(s.players[0].jail,1);s.stage='ready';s=travel(s);assert.equal(s.players[0].pos,8);assert.equal(s.players[0].jail,0);assert.equal(s.stage,'end');s.stage='ready';s=travel(s);assert.equal(s.players[0].pos,10);});
test('chance award and expense correctly resolve without extra action',()=>{let s=freshGame();s.players[0].pos=1;s=travel(s,[1,1],0);assert.equal(s.players[0].cash,16500);assert.equal(s.event.title,'城市更新獎勵');s=freshGame();s.players[0].pos=1;s=travel(s,[1,1],1);assert.equal(s.players[0].cash,14100);});
test('bankrupt turns are skipped and final survivor wins',()=>{let s=freshGame();s.players[1].bankrupt=true;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.turn,2);s=freshGame();s.players[1].bankrupt=s.players[2].bankrupt=true;s.turn=3;s.players[3].cash=0;s.players[3].pos=4;s=travel(s);assert.equal(s.stage,'finished');assert.equal(s.winner,0);});
test('40 round ending selects highest solvent net worth',()=>{let s=freshGame();s.round=40;s.turn=3;s.stage='end';s.players[2].cash=21000;s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'finished');assert.equal(s.winner,2);});
test('80 round limit waits until the configured final round',()=>{let s=freshGame({maxRounds:80});s.round=40;s.turn=3;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'ready');assert.equal(s.round,41);s.round=80;s.turn=3;s.stage='end';s.players[2].cash=21000;s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'finished');assert.equal(s.winner,2);});
test('custom and unlimited round limits are respected',()=>{let s=freshGame({maxRounds:3});s.round=3;s.turn=3;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'finished');assert.equal(s.round,4);s=freshGame({maxRounds:null});s.round=999;s.turn=3;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.stage,'ready');assert.equal(s.round,1000);});
test('inflation compounds once when the complete player round advances',()=>{let s=freshGame({count:2,inflationRate:1});s.turn=1;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.round,2);assert.equal(s.turn,0);assert.equal(s.priceIndex,1.01);assert.equal(s.inflationRate,1);});
test('inflation cards change the next-round rate without changing the current price index',()=>{let s=freshGame({count:2,inflationRate:1});s.players[0].pos=1;s=travel(s,[1,1],6);assert.equal(s.inflationRate,2);assert.equal(s.priceIndex,1);assert.equal(s.event.kind,'inflation');s.turn=1;s.stage='end';s=reducer(s,{type:'NEXT'});s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.round,2);assert.equal(s.priceIndex,1.02);});
test('inflation rate and price index stay within their floors and caps',()=>{let s=freshGame({count:2,inflationRate:0});s.players[0].pos=1;s=travel(s,[1,1],7);assert.equal(s.inflationRate,0);s.inflationRate=10;s.players[0].pos=1;s.stage='ready';s=travel(s,[1,1],6);assert.equal(s.inflationRate,10);s.priceIndex=9.99;s.turn=1;s.stage='end';s=reducer(s,{type:'NEXT'});assert.equal(s.priceIndex,MAX_PRICE_INDEX);});
test('property prices, rent, building, selling value, and net worth use the current index',()=>{let s=freshGame();s.priceIndex=1.5;s.lots[1]={owner:0,level:1};assert.equal(propertyPrice(s,TILES[1]),1650);assert.equal(rent(s,TILES[1]),891);assert.equal(buildCost(TILES[1],s),990);assert.equal(worth(s,0),17640);s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(canBuild(s,1),true);s=reducer(s,{type:'BUILD',id:1});const afterBuild=15000+inflationAmount(s,2000)-buildCost(TILES[1],s);assert.equal(s.players[0].cash,afterBuild);s=reducer(s,{type:'SELL',id:1});assert.equal(s.players[0].cash,afterBuild+Math.floor((TILES[1].price+2*Math.round(TILES[1].price*.6))*1.5*.5));});
test('passing GO and paying tax apply the current price index',()=>{let s=freshGame();s.priceIndex=1.5;s.players[0].pos=31;s=travel(s,[1,1]);assert.equal(s.players[0].cash,18000);s=freshGame();s.priceIndex=1.5;s.players[0].pos=4;s=travel(s,[1,1]);assert.equal(s.players[0].cash,15000-Math.round(1200*1.5));});
test('chance payouts and rent transfers are scaled consistently for both players',()=>{let s=freshGame();s.priceIndex=1.5;s.players[0].pos=1;s=travel(s,[1,1],0);assert.equal(s.event.amount,2250);assert.equal(s.players[0].cash,17250);s=freshGame({count:2});s.priceIndex=1.5;s.lots[1]={owner:0,level:1};s.turn=1;s.players[1].pos=31;s=travel(s,[1,1]);assert.equal(s.players[1].cash,17109);assert.equal(s.players[0].cash,15891);});
test('simulate 100 complete games: finite turns, no negative funds or invalid owners',()=>{let seed=17;const rnd=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n;};for(let g=0;g<100;g++){let s=freshGame(),actions=0;while(s.stage!=='finished'&&actions++<10000){if(s.skillOverflow){const holder=s.players[s.skillOverflow.playerId];s=reducer(s,{type:'RESOLVE_SKILL_OVERFLOW',cardId:holder.skillHand.at(-1)});}else if(s.stage==='ready')s=travel(s,[rnd(6)+1,rnd(6)+1],rnd(6));else if(s.stage==='decision')s=reducer(s,{type:rnd(4)?'BUY':'SKIP'});else if(s.stage==='end'){let t=TILES.find(t=>canBuild(s,t.id));if(t&&rnd(3)===0)s=reducer(s,{type:'BUILD',id:t.id});else s=reducer(s,{type:'NEXT'});}for(const p of s.players)assert.ok(p.cash>=0);for(const l of Object.values(s.lots))assert.equal(s.players[l.owner].bankrupt,false);}assert.equal(s.stage,'finished');assert.ok(actions<10000);}});

test('one die moves by its value and preserves the choice across turns',()=>{let s=reducer(freshGame(),{type:'SET_DICE_COUNT',count:1});const moving=reducer(s,{type:'ROLL',dice:[6],eventIndex:0});assert.equal(moving.remaining,6);assert.deepEqual(moving.dice,[6]);assert.match(moving.notice,/擲出 6，前進 6 格/);s=travel(s,[6]);assert.equal(s.players[0].pos,6);assert.equal(s.players[0].cash,13800);s=reducer(s,{type:'NEXT'});assert.equal(s.players[0].diceCount,1);assert.equal(s.players[1].diceCount,2);});
test('dice count cannot change after rolling, for AI, in jail, or to invalid values',()=>{const initial=freshGame();assert.strictEqual(reducer(initial,{type:'SET_DICE_COUNT',count:3}),initial);for(const edit of [s=>s.stage='moving',s=>s.turn=1,s=>s.players[0].jail=1]){const s=freshGame();edit(s);assert.strictEqual(reducer(s,{type:'SET_DICE_COUNT',count:1}),s);}});
test('roll rejects malformed dice and uses the selected count',()=>{const s=reducer(freshGame(),{type:'SET_DICE_COUNT',count:1});for(const dice of [[],[1,2],[0],[7],[1.5],null])assert.strictEqual(reducer(s,{type:'ROLL',dice}),s);const two=reducer(s,{type:'SET_DICE_COUNT',count:2});assert.equal(reducer(two,{type:'ROLL',dice:[6,6],eventIndex:0}).remaining,12);});

test('rent creates one paired emotion event with each player’s own reaction',()=>{let s=freshGame({count:2});s.players[0].pos=1;s.players[0].diceCount=1;s.lots[2]={owner:1,level:0};s=reducer(s,{type:'ROLL',dice:[1]});s=reducer(s,{type:'STEP'});const [event]=s.emotionEvents;assert.equal(event.priority,90);assert.deepEqual(event.players.map(({playerId,mood,amountDelta})=>({playerId,mood,amountDelta})),[{playerId:0,mood:'sad',amountDelta:-216},{playerId:1,mood:'happy',amountDelta:216}]);assert.equal(s.players[0].cash,14784);assert.equal(s.players[1].cash,15216);assert.equal(s.log.filter(entry=>entry.kind==='rent').length,1);});
test('landing emotion remains available after the next turn action',()=>{let s=freshGame({count:2});s.players[0].pos=1;s.players[0].diceCount=1;s.lots[2]={owner:1,level:0};s=reducer(s,{type:'ROLL',dice:[1]});s=reducer(s,{type:'STEP'});const rentEvent=s.emotionEvents[0];s=reducer(s,{type:'NEXT'});assert.deepEqual(s.emotionEvents,[]);assert.ok(s.emotionHistory.some(event=>event.id===rentEvent.id&&event.category==='rentPaid'));});

test('money emotion events cover buying, salary, chance awards and chance expenses',()=>{let s=freshGame();s.players[0].pos=1;s.players[0].diceCount=1;s=travel(s,[1]);s=reducer(s,{type:'BUY'});assert.equal(s.emotionEvents[0].category,'purchase');assert.equal(s.emotionEvents[0].players[0].amountDelta,-1200);s=freshGame();s.players[0].pos=31;s.players[0].diceCount=1;s=travel(s,[1]);assert.equal(s.emotionEvents[0].category,'salary');assert.equal(s.emotionEvents[0].players[0].amountDelta,2000);s=freshGame();s.players[0].pos=2;s.players[0].diceCount=1;s=travel(s,[1],0);assert.equal(s.emotionEvents[0].category,'windfall');assert.equal(s.emotionEvents[0].players[0].amountDelta,1500);s=freshGame();s.players[0].pos=2;s.players[0].diceCount=1;s=travel(s,[1],1);assert.equal(s.emotionEvents[0].category,'chanceExpense');assert.equal(s.emotionEvents[0].players[0].amountDelta,-900);});

test('unaffordable empty property emits a rotating hesitation emotion',()=>{let s=freshGame();s.players[0].cash=1000;s.players[0].diceCount=1;s=travel(s,[1]);assert.equal(s.players[0].pos,1);assert.equal(s.stage,'end');assert.equal(s.emotionEvents[0].category,'propertyUnaffordable');assert.equal(s.emotionEvents[0].players[0].mood,'anxious');assert.ok(s.emotionEvents[0].players[0].message);});
test('unaffordable empty property uses the inflation-adjusted price',()=>{let s=freshGame();s.priceIndex=1.5;s.players[0].cash=1600;s.players[0].diceCount=1;s=travel(s,[1]);assert.equal(propertyPrice(s,TILES[1]),1650);assert.equal(s.stage,'end');assert.equal(s.emotionEvents[0].category,'propertyUnaffordable');});

test('tax, building and voluntary sale emit the matching emotion categories',()=>{let s=freshGame();s.players[0].pos=5;s.players[0].diceCount=1;s=travel(s,[1]);assert.equal(s.emotionEvents[0].category,'tax');assert.equal(s.emotionEvents[0].players[0].mood,'anxious');s=freshGame();s.stage='end';s.selected=2;s.buildAvailable=true;s.players[0].pos=2;s.lots[2]={owner:0,level:0};s=reducer(s,{type:'BUILD',id:2});assert.equal(s.emotionEvents[0].category,'construction');assert.equal(s.emotionEvents[0].players[0].amountDelta,-720);s.stage='ready';s=reducer(s,{type:'SELL',id:2});assert.equal(s.emotionEvents[0].category,'sale');assert.ok(s.emotionEvents[0].players[0].amountDelta>0);});

test('automatic sale, partial payment and bankruptcy remain separate prioritized events',()=>{let s=freshGame();s.players[0].pos=5;s.players[0].diceCount=1;s.players[0].cash=0;s.lots[1]={owner:0,level:0};s=travel(s,[1]);assert.deepEqual(s.emotionEvents.map(({category,priority})=>({category,priority})),[{category:'sale',priority:60},{category:'tax',priority:55},{category:'bankruptcy',priority:100}]);assert.equal(s.emotionEvents[2].players[0].amountDelta,-650);assert.equal(s.players[0].bankrupt,true);});

test('chance and fund events draw a skill card without replacing the original event',()=>{let s=freshGame();s.players[0].pos=1;s=travel(s,[1,1],0);assert.equal(s.stage,'end');assert.equal(s.players[0].skillHand.length,1);assert.equal(typeof s.event.skillCardName,'string');assert.equal(s.event.title,'城市更新獎勵');assert.match(s.notice,/獲得技能卡/);});
test('full skill hand draws one extra card and opens an overflow decision',()=>{let s=freshGame();s.players[0].skillHand=['trap','slow','subsidy'];s.players[0].pos=13;s.players[0].diceCount=1;s=travel(s,[1]);assert.equal(s.players[0].skillHand.length,4);assert.deepEqual(s.skillOverflow,{playerId:0});assert.ok(s.log.some(entry=>/獲得技能卡/.test(entry.text)));});
 test('active skill cards are consumed once per turn and subsidy applies inflation',()=>{let s=freshGame();s.priceIndex=1.5;s.players[0].skillHand=['subsidy'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'subsidy'});assert.equal(s.players[0].cash,16200);assert.deepEqual(s.players[0].skillHand,[]);assert.equal(s.players[0].skillUsedThisTurn,true);assert.equal(s.skillDiscard.at(-1),'subsidy');assert.strictEqual(reducer(s,{type:'USE_SKILL_CARD',cardId:'subsidy'}),s);});
 test('lucky redraw discards a selected card and draws one replacement',()=>{let s=freshGame();s.players[0].skillHand=['redraw','slow'];s.skillDeck=['subsidy'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'redraw',discardCardId:'slow'});assert.deepEqual(s.players[0].skillHand,['subsidy']);assert.deepEqual(s.skillDiscard,['redraw','slow']);assert.equal(s.players[0].skillUsedThisTurn,true);assert.ok(s.log.some(entry=>/放棄技能卡「龜速卡」/.test(entry.text)));});
 test('lucky redraw with no other card draws directly',()=>{let s=freshGame();s.players[0].skillHand=['redraw'];s.skillDeck=['subsidy'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'redraw'});assert.deepEqual(s.players[0].skillHand,['subsidy']);assert.deepEqual(s.skillDiscard,['redraw']);});
 test('lucky redraw reshuffles the discard pile when the deck is empty',()=>{let s=freshGame();s.players[0].skillHand=['redraw','slow'];s.skillDeck=[];s.skillDiscard=['trap'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'redraw',discardCardId:'slow'});assert.equal(s.players[0].skillHand.length,1);assert.equal(s.skillDiscard.length,0);assert.equal(s.skillDeck.length,2);});
 test('lucky redraw rejects missing or invalid discard choices',()=>{let s=freshGame();s.players[0].skillHand=['redraw','slow'];const unchanged=reducer(s,{type:'USE_SKILL_CARD',cardId:'redraw'});assert.strictEqual(unchanged,s);assert.strictEqual(reducer(s,{type:'USE_SKILL_CARD',cardId:'redraw',discardCardId:'subsidy'}),s);});
test('slow card limits the target to one step for three target turns',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:1});assert.equal(s.players[1].slowTurns,3);s.stage='end';s=reducer(s,{type:'NEXT'});s=reducer(s,{type:'ROLL',dice:[6,6]});assert.equal(s.remaining,1);s=reducer(s,{type:'STEP'});assert.equal(s.players[1].pos,1);assert.equal(s.players[1].slowTurns,2);});
test('slow card can target its user and still applies the normal three-turn limit',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:0});assert.equal(s.players[0].slowTurns,3);assert.equal(s.pendingSkill,null);assert.deepEqual(s.players[0].skillHand,[]);});
test('slow card cannot be applied again while the target is already slowed',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow','slow'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:0});assert.equal(s.players[0].slowTurns,3);s.players[0].skillUsedThisTurn=false;const unchanged=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:0});assert.strictEqual(unchanged,s);assert.equal(s.players[0].slowTurns,3);});
test('teleport rejects an invalid destination before consuming the card',()=>{let s=freshGame({count:2});s.players[0].skillHand=['teleport'];const unchanged=reducer(s,{type:'USE_SKILL_CARD',cardId:'teleport',targetId:1,targetPosition:24});assert.strictEqual(unchanged,s);assert.deepEqual(s.players[0].skillHand,['teleport']);});
test('rent double requires an owned property and cannot be re-armed while active',()=>{let s=freshGame({count:2});s.players[0].skillHand=['rent-double'];let unchanged=reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-double'});assert.strictEqual(unchanged,s);s.players[0].skillHand=['rent-double'];s.lots[1]={owner:0,level:0};s=reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-double'});assert.equal(s.players[0].rentMultiplier,2);s.stage='ready';s.players[0].skillUsedThisTurn=false;s.players[0].skillHand=['rent-double'];assert.strictEqual(reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-double'}),s);});
test('rent shield cannot be re-armed while the previous shield is active',()=>{let s=freshGame({count:2});s.players[0].skillHand=['rent-shield'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-shield'});assert.equal(s.players[0].rentShield,1);s.stage='ready';s.players[0].skillUsedThisTurn=false;s.players[0].skillHand=['rent-shield'];assert.strictEqual(reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-shield'}),s);});
test('birthday card rejects use when no other player is alive',()=>{let s=freshGame({count:2});s.players[0].skillHand=['birthday'];s.players[1].bankrupt=true;assert.strictEqual(reducer(s,{type:'USE_SKILL_CARD',cardId:'birthday'}),s);});
test('land swap exchanges ownership while preserving building levels',()=>{let s=freshGame({count:2});s.lots[1]={owner:0,level:2};s.lots[2]={owner:1,level:1};s.players[0].skillHand=['land-swap'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'land-swap',ownLotId:1,targetLotId:2});assert.equal(s.lots[1].owner,1);assert.equal(s.lots[2].owner,0);assert.equal(s.lots[1].level,2);assert.equal(s.lots[2].level,1);});
test('targeted skill cards show emotions for both the user and target',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:1});assert.deepEqual(s.emotionEvents[0].players.map(({playerId,mood})=>({playerId,mood})),[{playerId:0,mood:'proud'},{playerId:1,mood:'surprised'}]);s=freshGame({count:2});s.lots[1]={owner:0,level:0};s.lots[2]={owner:1,level:0};s.players[0].skillHand=['land-swap'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'land-swap',ownLotId:1,targetLotId:2});assert.deepEqual(s.emotionEvents[0].players.map(({playerId,mood})=>({playerId,mood})),[{playerId:0,mood:'proud'},{playerId:1,mood:'surprised'}]);});
test('a skill with a reaction window shows both emotions before the response',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s.players[1].skillHand=['counter'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:1});assert.equal(s.pendingSkill.targetId,1);assert.deepEqual(s.emotionEvents[0].players.map(({playerId})=>playerId),[0,1]);});
test('rent shield prevents the next rent payment after inflation rules are applied',()=>{let s=freshGame({count:2});s.players[0].pos=1;s.players[0].diceCount=1;s.lots[2]={owner:1,level:0};s.players[0].skillHand=['rent-shield'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'rent-shield'});s=travel(s,[1]);assert.equal(s.players[0].cash,15000);assert.equal(s.players[1].cash,15000);assert.equal(s.players[0].rentShield,0);});
test('passing or landing on a city fund tile draws exactly one skill card',()=>{let s=freshGame();s.players[0].pos=13;s.players[0].diceCount=2;s=travel(s,[1,1]);assert.equal(s.players[0].pos,15);assert.equal(s.players[0].skillHand.length,1);assert.ok(s.log.some(entry=>/城市基金格/.test(entry.text)));});
test('full skill hand draws first, then requires discarding back to three',()=>{let s=freshGame();s.players[0].pos=13;s.players[0].diceCount=1;s.players[0].skillHand=['trap','slow','subsidy'];s=travel(s,[1]);assert.equal(s.players[0].skillHand.length,4);assert.deepEqual(s.skillOverflow,{playerId:0});const discardId=s.players[0].skillHand[0];s=reducer(s,{type:'RESOLVE_SKILL_OVERFLOW',cardId:discardId});assert.equal(s.players[0].skillHand.length,3);assert.equal(s.skillOverflow,null);assert.equal(s.skillDiscard.at(-1),discardId);});
test('overflow card can be used immediately and restores the hand limit',()=>{let s=freshGame();s.players[0].pos=13;s.players[0].diceCount=1;s.players[0].skillHand=['trap','slow','subsidy'];s=travel(s,[1]);const cash=s.players[0].cash;s=reducer(s,{type:'USE_SKILL_CARD',cardId:'subsidy',overflowUse:true});assert.equal(s.players[0].cash,cash+800);assert.equal(s.players[0].skillHand.length,3);assert.equal(s.skillOverflow,null);assert.equal(s.players[0].skillUsedThisTurn,true);});
test('teleport moves a target to a legal tile and resolves its destination without drawing another skill card',()=>{let s=freshGame({count:2});s.players[0].skillHand=['teleport'];s.players[1].pos=1;s=reducer(s,{type:'USE_SKILL_CARD',cardId:'teleport',targetId:1,targetPosition:3});assert.equal(s.players[1].pos,3);assert.equal(s.players[0].skillUsedThisTurn,true);assert.equal(s.pendingSkill,null);assert.equal(s.players[0].skillHand.length,0);assert.equal(s.players[1].skillHand.length,0);assert.equal(s.event.title,'社區公益');assert.equal(s.event.skillCardName,undefined);});
test('counter card cancels a pending single-target skill',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s.players[1].skillHand=['counter'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:1});assert.deepEqual(s.pendingSkill,{sourceId:0,targetId:1,cardId:'slow',targetPosition:null,ownLotId:undefined,targetLotId:undefined});s=reducer(s,{type:'RESPOND_SKILL',playerId:1,response:'counter'});assert.equal(s.pendingSkill,null);assert.equal(s.players[1].slowTurns,0);assert.deepEqual(s.players[1].skillHand,[]);assert.deepEqual(s.skillDiscard,['slow','counter']);});
test('reflect card redirects a pending single-target skill to the attacker',()=>{let s=freshGame({count:2});s.players[0].skillHand=['slow'];s.players[1].skillHand=['reflect'];s=reducer(s,{type:'USE_SKILL_CARD',cardId:'slow',targetId:1});s=reducer(s,{type:'RESPOND_SKILL',playerId:1,response:'reflect'});assert.equal(s.pendingSkill,null);assert.equal(s.players[0].slowTurns,3);assert.equal(s.players[1].slowTurns,0);assert.deepEqual(s.skillDiscard,['slow','reflect']);});
test('AI players can use active skill cards through the reducer',()=>{let s=freshGame({count:2,players:[{human:false},{human:false}]});s.players[0].skillHand=['subsidy'];const cash=s.players[0].cash;s=reducer(s,{type:'USE_SKILL_CARD',cardId:'subsidy'});assert.equal(s.players[0].cash,cash+800);assert.equal(s.players[0].skillUsedThisTurn,true);});
