import test from 'node:test';
import assert from 'node:assert/strict';
import {freshGame,reducer} from './game.js';
import {saveManual,listSaves,readManual,saveAuto,readAuto,TTL,MANUAL_KEY,validGame} from './storage.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
test('ten versions require confirmation; replacement removes oldest only',()=>{const db=memory();for(let i=0;i<10;i++)saveManual(freshGame(),`save ${i}`,false,db,100+i);assert.throws(()=>saveManual(freshGame(),'extra',false,db,111));const entries=saveManual(freshGame(),'extra',true,db,111);assert.equal(entries.length,10);assert.equal(entries.at(-1).name,'save 1');});
test('expiry is exact and loading does not extend retention',()=>{const db=memory();const [e]=saveManual(freshGame(),'a',false,db,100);assert.ok(readManual(e.id,db,100+TTL-1));assert.throws(()=>readManual(e.id,db,100+TTL));assert.deepEqual(listSaves(db,100+TTL),[]);saveAuto(freshGame(),db,100);assert.equal(readAuto(db,100+TTL),null);});
test('mid-move save resumes without duplicate GO reward and retains chance outcome',()=>{const db=memory();let game=freshGame();game.players[0].pos=31;game=reducer(game,{type:'ROLL',dice:[2,2],eventIndex:0});game=reducer(game,{type:'STEP'});const [entry]=saveManual(game,'moving',false,db,100);let restored=reducer(freshGame(),{type:'LOAD',game:readManual(entry.id,db,101)});while(restored.stage==='moving')restored=reducer(restored,{type:'STEP'});assert.equal(restored.players[0].cash,18500);assert.equal(restored.players[0].pos,3);assert.equal(game.remaining,3);});
test('legacy saves without a round limit migrate to the default',()=>{const db=memory();const legacy=freshGame();delete legacy.maxRounds;const [entry]=saveManual(legacy,'legacy',false,db,100);const restored=reducer(freshGame({maxRounds:80}),{type:'LOAD',game:readManual(entry.id,db,101)});assert.equal(restored.maxRounds,40);});
test('legacy saves without inflation fields migrate to zero percent and the base index',()=>{const legacy=freshGame();delete legacy.inflationRate;delete legacy.priceIndex;assert.equal(validGame(legacy),true);const restored=reducer(freshGame(),{type:'LOAD',game:legacy});assert.equal(restored.inflationRate,0);assert.equal(restored.priceIndex,1);});
test('moving saves accept new inflation event cards but reject out-of-range card indices',()=>{const moving=reducer(freshGame(),{type:'ROLL',dice:[1,1],eventIndex:7});assert.equal(validGame(moving),true);moving.eventIndex=8;assert.equal(validGame(moving),false);});
test('damaged entries are excluded and failed writes preserve saves',()=>{const db=memory();db.setItem(MANUAL_KEY,JSON.stringify([{id:'bad',name:'bad',savedAt:1,game:{version:1}}]));assert.deepEqual(listSaves(db,2),[]);saveManual(freshGame(),'keep',false,db,3);const before=db.getItem(MANUAL_KEY);const full={...db,setItem(){throw new Error('quota');}};assert.throws(()=>saveManual(freshGame(),'fail',false,full,4));assert.equal(db.getItem(MANUAL_KEY),before);});

test('single-die manual and automatic saves preserve preference and resume across GO',()=>{const db=memory();let s=reducer(freshGame(),{type:'SET_DICE_COUNT',count:1});s.players[0].pos=31;s=reducer(s,{type:'ROLL',dice:[2],eventIndex:0});s=reducer(s,{type:'STEP'});saveAuto(s,db,100);assert.deepEqual(readAuto(db,101),s);const [entry]=saveManual(s,'single',false,db,100);let restored=reducer(freshGame(),{type:'LOAD',game:readManual(entry.id,db,101)});restored=reducer(restored,{type:'STEP'});assert.equal(restored.players[0].pos,1);assert.equal(restored.players[0].cash,17000);assert.equal(restored.players[0].diceCount,1);assert.equal(restored.stage,'decision');});
test('legacy dice preferences default to two; invalid dice saves are rejected',()=>{const legacy=freshGame();legacy.players.forEach(p=>delete p.diceCount);assert.ok(validGame(legacy));assert.equal(reducer(freshGame(),{type:'LOAD',game:legacy}).players[0].diceCount,2);for(const dice of [[],[1,2,3],[0],[7]])assert.equal(validGame({...legacy,dice}),false);legacy.players[0].diceCount=3;assert.equal(validGame(legacy),false);});
test('legacy saves without skill card fields migrate to empty hands and a fresh deck',()=>{const legacy=freshGame();delete legacy.skillDeck;delete legacy.skillDiscard;legacy.players.forEach(p=>{delete p.skillHand;delete p.skillUsedThisTurn;delete p.slowTurns;delete p.stayTurns;delete p.rentShield;delete p.rentMultiplier;});assert.equal(validGame(legacy),true);const restored=reducer(freshGame(),{type:'LOAD',game:legacy});assert.deepEqual(restored.players.map(p=>p.skillHand),[[],[],[],[]]);assert.equal(restored.skillDeck.length,17);assert.deepEqual(restored.skillDiscard,[]);});
